### PR TITLE
Fix a race condition that could cause an infinite loop

### PR DESCRIPTION
**Pull request by mourner**
A port of https://github.com/mapbox/earcut/pull/108

The test code change is about not comparing "area deviation" if the number of expected triangles is 0 (it doesn't make sense).

### CODE REVIEW

**Comment by mourner** [comment]
@mrgreywater yes, see the comment above.

**Comment by mourner** [comment]
@mrgreywater ah, good point. I disabled it for libtess too because it was failing the build, but I rolled that back in the last commit.

**Comment by mrgreywater** [comment]
libtess is now showing a deviation of -200% for issue107, which is unexpected, since it should be a positive value. But I can debug that later when it's merged if necessary.

**Comment by mourner** [comment]
@mrgreywater found the issue, fixed now.

**Pull request merged**
