### PR TITLE
Add Visual Studio 2013 and 2015 support

### PR DESCRIPTION
**Pull request by mrgreywater**
This adds support for the Microsoft Visual C++ Compiler including the tests, viz and bench. It sadly requires some MSVC specific hacks to make it work. 

In particular MSVC doesn't like the large inline initialization of std::vectors for the fixtures and just hangs indefinitely (>20 min) trying to optimize them, so it is required to disable optimization for those files. I don't particularly like it, but the only other way to resolve this are either use resource files, using static c-arrays, or loading the fixtures at runtime from the working directory. But this would have downsides aswell.

This PR replaces lots of usages of printf with c++ streams, as they were using non-standard formatting options that are not available in msvc.

It also changes very few functions that use c++14 features that were not available with VC12 yet.

VC14 Release x86 - Windows 10 x64
```
+----------------+--------------------+--------------------+
| Polygon        | earcut             | libtess2           |
+----------------+--------------------+--------------------+
| bad_hole       |      133.717 ops/s |       59.204 ops/s |
| building       |    1.458.977 ops/s |      133.365 ops/s |
| degenerate     |    3.179.523 ops/s |      202.700 ops/s |
| dude           |       77.824 ops/s |       31.110 ops/s |
| empty_square   |    2.012.103 ops/s |      192.166 ops/s |
| water_huge     |          102 ops/s |          100 ops/s |
| water_huge2    |           47 ops/s |          133 ops/s |
| water          |        1.127 ops/s |          264 ops/s |
| water2         |        1.002 ops/s |        1.431 ops/s |
| water3         |       26.433 ops/s |       14.437 ops/s |
| water3b        |      322.550 ops/s |       92.996 ops/s |
| water4         |        4.052 ops/s |        2.966 ops/s |
+----------------+--------------------+--------------------+
```
VC12 Release x86 - Windows 10 x64
```
+----------------+--------------------+--------------------+
| Polygon        | earcut             | libtess2           |
+----------------+--------------------+--------------------+
| bad_hole       |      137.110 ops/s |       58.447 ops/s |
| building       |    1.558.104 ops/s |      129.256 ops/s |
| degenerate     |    3.483.275 ops/s |      192.088 ops/s |
| dude           |       73.920 ops/s |       30.810 ops/s |
| empty_square   |    2.092.300 ops/s |      184.995 ops/s |
| water_huge     |          104 ops/s |          100 ops/s |
| water_huge2    |           48 ops/s |          134 ops/s |
| water          |        1.164 ops/s |          270 ops/s |
| water2         |          953 ops/s |        1.443 ops/s |
| water3         |       25.752 ops/s |       14.466 ops/s |
| water3b        |      333.720 ops/s |       91.763 ops/s |
| water4         |        4.043 ops/s |        2.901 ops/s |
+----------------+--------------------+--------------------+
```
GCC 4.9.2 -O3 -march=native - Ubuntu 14.04
```
+----------------+--------------------+--------------------+
| Polygon        | earcut             | libtess2           |
+----------------+--------------------+--------------------+
| bad_hole       |      164.130 ops/s |       19.787 ops/s |
| building       |    1.819.283 ops/s |       51.033 ops/s |
| degenerate     |    3.543.121 ops/s |       89.198 ops/s |
| dude           |      108.706 ops/s |       11.556 ops/s |
| empty_square   |    2.406.061 ops/s |       75.893 ops/s |
| water_huge     |           88 ops/s |           60 ops/s |
| water_huge2    |           43 ops/s |           76 ops/s |
| water          |        1.206 ops/s |          160 ops/s |
| water2         |        1.385 ops/s |          709 ops/s |
| water3         |       38.820 ops/s |        5.360 ops/s |
| water3b        |      431.561 ops/s |       32.419 ops/s |
| water4         |        5.000 ops/s |        1.293 ops/s |
+----------------+--------------------+--------------------+
```
Interestingly libtess2 seems about twice as fast with Windows/MSVC (I guess the Windows 10 heap allocator is faster?)

### CODE REVIEW

**Comment by jfirebaugh** [comment]
:+1: 

Let me know when this is good to go and I'll merge.

**Comment by mrgreywater** [comment]
Are you ok with all the MSVC optimization macros? I really don't like it. I'm thinking about putting the tests in header instead of cpp files, so I can wrap around the optimization disabling macros where the tests are included. But I'm not so sure if thats cleaner.

I hate compiler bugs -.-

**Comment by jfirebaugh** [comment]
I'm not too worried about it. These files are autogenerated and we can easily switch if we find a better solution.

Although, that reminds me, can you change https://github.com/mapbox/earcut.hpp/blob/master/test/convert_tests.js to generate the desired lines? (Sorry this part is not well documented -- it should have an explanation of how to regenerate the fixtures, which requires a local checkout of the js fixtures and node.)

**Comment by mrgreywater** [comment]
will do, I missed that generator.

**Comment by mrgreywater** [comment]
If you're fine with the new changes, it's ready.

**Comment by mourner** [comment]
:+1:

**Pull request merged**
